# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a541a57061b256bdd1984d1727541a2fbdc084b51bd3e48215aa37f2f500abb88156fb5ceb96bb74b0d9650bfaeb4ccfa4d17c14158ab5a7e8d1374e3760304

test:
  secret_key_base: 91d63405ce44a1f4cd72042ad279488f92fe70edce46e6143f534a5c7413d6bcaa518e53547e944b1cac9061f4d07e176330fc03e330948a002d03851d58cc95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
